export const domainOptions = [
  { value: "Software Development", label: "Software Development" },
  { value: "Data Science", label: "Data Science" },
  { value: "Machine Learning / AI", label: "Machine Learning / AI" },
  { value: "DevOps / Cloud", label: "DevOps / Cloud" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Product Management", label: "Product Management" },
  { value: "Project Management", label: "Project Management" },
  { value: "UI / UX Design", label: "UI / UX Design" },
  { value: "Marketing", label: "Marketing" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Sales", label: "Sales" },
  { value: "Business Development", label: "Business Development" },
  { value: "Finance", label: "Finance" },
  { value: "Accounting", label: "Accounting" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Operations", label: "Operations" },
  { value: "Customer Support", label: "Customer Support" },
  { value: "Education", label: "Education" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Legal", label: "Legal" },
  { value: "Consulting", label: "Consulting" },
  { value: "Research", label: "Research" },
  { value: "Content Writing", label: "Content Writing" },
  { value: "Media & Communications", label: "Media & Communications" },
  { value: "Supply Chain / Logistics", label: "Supply Chain / Logistics" },
  { value: "Engineering (Non-Software", label: "Engineering (Non-Software)" },
  { value: "Construction", label: "Construction" },
  { value: "Government / Public Sector", label: "Government / Public Sector" },
  { value: "Hospitality / Tourism", label: "Hospitality / Tourism" },
  { value: "Retail / E-commerce", label: "Retail / E-commerce" },
];