export const domainOptions = [
  { value: "software-development", label: "Software Development" },
  { value: "data-science", label: "Data Science" },
  { value: "machine-learning-ai", label: "Machine Learning / AI" },
  { value: "devops-cloud", label: "DevOps / Cloud" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "product-management", label: "Product Management" },
  { value: "project-management", label: "Project Management" },
  { value: "design-ui-ux", label: "UI / UX Design" },
  { value: "marketing", label: "Marketing" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "sales", label: "Sales" },
  { value: "business-development", label: "Business Development" },
  { value: "finance", label: "Finance" },
  { value: "accounting", label: "Accounting" },
  { value: "human-resources", label: "Human Resources" },
  { value: "operations", label: "Operations" },
  { value: "customer-support", label: "Customer Support" },
  { value: "education", label: "Education" },
  { value: "healthcare", label: "Healthcare" },
  { value: "legal", label: "Legal" },
  { value: "consulting", label: "Consulting" },
  { value: "research", label: "Research" },
  { value: "content-writing", label: "Content Writing" },
  { value: "media-communications", label: "Media & Communications" },
  { value: "supply-chain-logistics", label: "Supply Chain / Logistics" },
  { value: "engineering-non-software", label: "Engineering (Non-Software)" },
  { value: "construction", label: "Construction" },
  { value: "government-public-sector", label: "Government / Public Sector" },
  { value: "hospitality-tourism", label: "Hospitality / Tourism" },
  { value: "retail-ecommerce", label: "Retail / E-commerce" },
];